### PR TITLE
Add support for secure cookies to fix issue #8

### PR DESCRIPTION
**Pull request by jkoehl**
A fix for issue #8

(sorry I wasn't sure how to actually run the tests so I didn't add a test)

### CODE REVIEW

**Comment by twillis** [comment]
Hey @jkoehl , I'm working on cleaning some of this stuff up and I came across this again. Trying to figure out how to test this. was there a url that was failing for you without this functionality? is it possible for me to take a look at it?

**Comment by jkoehl** [comment]
As I recall all I had to do was attempt to have a response that sets a cookie with the secure flag such as:

```
set-cookie:1_bcsec="970cbf5efb0e4cad61057b8bb5c7174d5318666e3001!userid_type:int"; Path=/; Secure
```

**Comment by twillis** [comment]
ah ok. I'm gonna test this proper then. thanks for the speedy reply

**Comment by twillis** [comment]
and here's the test changes if you are curious. https://github.com/twillis/webobtoolkit/commit/b61c44dbe3f6b0c4936cb09c5278785b2df3340f

there's not going to be a release for a while though. I need to get proper docs for this thing. and clean up other stuff.

**Pull request merged**
